### ISSUE TITLE
ray.exceptions.RayTaskError(DistBackendError): ray::WorkerDict.ref_init_model() (pid=3829666, ip=192.168.4.25, actor_id=3d6e5c6ffd510f1a1f6e1dc101000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0x7fbb159ef040>)

### ISSUE THREAD

**Issue by JianxXiong** [verl-project/verl#2044]
File "/root/test/project/verl/single_controller/ray/base.py", line 432, in func
    return getattr(self.worker_dict[key], name)(*args, **kwargs)
  File "/root/test/project/verl/single_controller/base/decorator.py", line 207, in inner
    return func(*args, **kwargs)
  File "/root/test/project/verl/workers/fsdp_workers.py", line 349, in init_model
    self._build_model_optimizer(
  File "/root/test/project/verl/workers/fsdp_workers.py", line 230, in _build_model_optimizer
    dist.barrier()
  File "/root/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4551, in barrier
    work = group.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.hpp:268, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.21.5
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 1 'invalid argument'

How can I solve this problem?

**Comment by JianxXiong** [comment]
I have solved this problem! It's caused by the incorrect version of the nccl package in my conda environment.

**Comment by JoeZJH** [comment]
> I have solved this problem! It's caused by the incorrect version of the nccl package in my conda environment.

@JianxXiong Good job!  Could you please share your solution here? I have the same problem.

**Comment by JianxXiong** [comment]
> > I have solved this problem! It's caused by the incorrect version of the nccl package in my conda environment.
> 
> [@JianxXiong](https://github.com/JianxXiong) Good job! Could you please share your solution here? I have the same problem.

I tried different versions of nvidia-nccl-cu12 package, and find a higher version works, which is incompatible with my torch, however, no errors occur.

**Comment by JoeZJH** [comment]
> > > I have solved this problem! It's caused by the incorrect version of the nccl package in my conda environment.
> > 
> > 
> > [@JianxXiong](https://github.com/JianxXiong) Good job! Could you please share your solution here? I have the same problem.
> 
> I tried different versions of nvidia-nccl-cu12 package, and find a higher version works, which is incompatible with my torch, however, no errors occur.

Thanks for your reply!
