### ISSUE TITLE
CPU OOM during first training step | ray.exceptions.OutOfMemoryError

### ISSUE THREAD

**Issue by tobiashaab** [verl-project/verl#2245]
# CPU OOM Error

## Description

I am encountering a CPU OOM Error. Said error constantly appears during the very first training steps/ initialization (see logs below).

Using `vllm==0.8.3` and the latest `verl` causes the program to crash earlier. With `verl==0.3` and `vllm==0.6.3` it always reaches the very first training step, then crashes due to the CPU OOM error.
 
I have tried several potential fixes that were suggested on similair issues but none of them worked - which is why I decided to open a new one.

Any help would be appreciated!

### Attempted Fixes:
- Tested it on the `vllm` versions `0.8.1`, `0.8.3` and `0.6.3`.
- Added `export VLLM_ATTENTION_BACKEND=XFORMERS`
- Added `export VLLM_USE_V1=0`
- Added `actor_rollout_ref.rollout.free_cache_engine=False`
- Used three different models: `Qwen-2.5-7B-Instruct`, `Qwen-2.5-1.5B`, `DeepSeek-R1-Distill-Qwen-1.5B`
- Set `actor_rollout_ref.rollout.gpu_memory_utilization=0.5`
- Set `actor_rollout_ref.actor.ppo_micro_batch_size=2`
- Set `actor_rollout_ref.rollout.log_prob_micro_batch_size=2`
- Downgraded `verl` to `v0.3`
- Tried the following commands:
```python
export VLLM_COMMIT=227578480d71fc94ef46ca77fb69496412158d68
sudo pip install vllm --pre --extra-index-url https://wheels.vllm.ai/${VLLM_COMMIT}
git clone -b verl_v1 https://github.com/hiyouga/vllm.git
sudo cp -r vllm/vllm/ /usr/local/lib/python3.12/dist-packages/
```

Using the last script *did* help with  `vllm==0.8.3` and the latest `verl` to some extend. It no longer crashes at the point listed in the logs below. Instead, it now fails at the same point as `verl==0.3` and `vllm==0.6.3`.

### Default script:
<details>
<summary>script.sh</summary>

```python
export N_GPUS=8
export BASE_MODEL=./Qwen2.5-7B-Instruct
export DATA_DIR=./data/gsm8k
export ROLLOUT_TP_SIZE=2
export EXPERIMENT_NAME=gsm8k_qwen2.5-7B-Instruct
export HYDRA_FULL_ERROR=1
export RAY_DEDUP_LOGS=0
export NCCL_P2P_LEVEL=NVL

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/test.parquet \
    data.train_batch_size=128 \
    data.val_batch_size=640 \
    data.max_prompt_length=256 \
    data.max_response_length=1024 \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size=8 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0.001 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=8 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP_SIZE \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=2 \
    actor_rollout_ref.ref.fsdp_config.param_offload=False \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['console'] \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=$N_GPUS \
    trainer.nnodes=1 \
    trainer.save_freq=500 \
    trainer.test_freq=10 \
    trainer.project_name=TinyZero \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.total_training_steps=302 \
    trainer.total_epochs=1 2>&1 | tee verl_demo.log \
    actor_rollout_ref.rollout.disable_log_stats=False
```
</details>

### Diagnosis
<details>
<summary>diagnosis.py</summary>

```python
----------Python Info----------
Version      : 3.12.11
Compiler     : GCC 1.2.0
Build        : ('main', 'Jun  5 2025 13:09:17')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 25.1
Directory    : /home/dense/miniconda3/envs/verl_debug/lib/python3.12/site-packages/pip
vllm         : 0.8.3
sglang       : not found.
ray          : 2.47.1
torch        : 2.6.0+cu124
----------verl Info-----------
Version      : 0.4.0.dev
Directory    : /home/dense/tobhaab/debug_verl/verl/verl
Commit Hash  : e96f0fbf44a50a302ddea0118e76d40cc9aa4fff
----------Platform Info----------
Platform     : Linux-6.8.0-60-generic-x86_64-with-glibc2.35
system       : Linux
node         : meghan
release      : 6.8.0-60-generic
version      : #63~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 22 19:00:15 UTC 2
----------Environment----------
CUDA Runtime : 12.4
CUDA Compiler : Cuda compilation tools, release 12.2, V12.2.91
----------System Info----------
CPU Memory      : 503.71 GB
GPU Count       : 8
GPU 1   Type    : NVIDIA RTX A6000
GPU 1   Memory  : 47.99 GB
GPU 2   Type    : NVIDIA RTX A6000
GPU 2   Memory  : 47.99 GB
GPU 3   Type    : NVIDIA RTX A6000
GPU 3   Memory  : 47.99 GB
GPU 4   Type    : NVIDIA RTX A6000
GPU 4   Memory  : 47.99 GB
GPU 5   Type    : NVIDIA RTX A6000
GPU 5   Memory  : 47.99 GB
GPU 6   Type    : NVIDIA RTX A6000
GPU 6   Memory  : 47.99 GB
GPU 7   Type    : NVIDIA RTX A6000
GPU 7   Memory  : 47.99 GB
GPU 8   Type    : NVIDIA RTX A6000
GPU 8   Memory  : 47.99 GB
```

</details>

### Logs
<details>
<summary>Logs of vllm==0.8.3 and verl==0.4</summary>

_Note: I have sanitized the logs by removing repetitive lines and shortening the full traceback for clarity._

```python
[...]
(WorkerDict pid=904529) Monkey patch _flash_attention_forward in transformers.integrations.flash_attention
(WorkerDict pid=904529) Skipping monkey patch for Qwen2ForCausalLM as use_fused_kernels is False or fused_kernels_backend is torch
(WorkerDict pid=904336) Total steps: 302, num_warmup_steps: 0
(WorkerDict pid=904336) Actor use_remove_padding=True
(WorkerDict pid=904336) Actor use_fused_kernels=False
(WorkerDict pid=904529) NCCL version 2.21.5+cuda12.4
(WorkerDict pid=904526) WARNING 06-27 13:10:19 [topk_topp_sampler.py:69] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
Error executing job with overrides: []
Traceback (most recent call last):
[...]
  File "/home/miniconda3/envs/verl_debug/lib/python3.12/site-packages/vllm/v1/core/kv_cache_utils.py", line 480, in check_enough_kv_cache_memory
    raise ValueError("No available memory for the cache blocks. "
ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
```

</details>

<details>
<summary>Logs of vllm==0.6.3 and verl==0.3</summary>

_Note: I have sanitized the logs by shortening the full traceback for clarity._

```python
[...]
(WorkerDict pid=915957) local rank 0
(WorkerDict pid=915956) local rank 0
(WorkerDict pid=915954) NCCL version 2.20.5+cuda12.4
(WorkerDict pid=915958) NCCL version 2.20.5+cuda12.4
(WorkerDict pid=915956) NCCL version 2.20.5+cuda12.4
(WorkerDict pid=915761) before init cache memory allocated: 11.4536448GB, reserved: 11.584667648GB
(WorkerDict pid=915761) after init cache memory allocated: 26.198851584GB, reserved: 26.38217216GB
(WorkerDict pid=915954) kwargs: {'n': 5, 'logprobs': 0, 'max_tokens': 1024, 'detokenize': False, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(WorkerDict pid=915958) kwargs: {'n': 5, 'logprobs': 0, 'max_tokens': 1024, 'detokenize': False, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(WorkerDict pid=915956) kwargs: {'n': 5, 'logprobs': 0, 'max_tokens': 1024, 'detokenize': False, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(WorkerDict pid=915959) kwargs: {'n': 5, 'logprobs': 0, 'max_tokens': 1024, 'detokenize': False, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(WorkerDict pid=915955) kwargs: {'n': 5, 'logprobs': 0, 'max_tokens': 1024, 'detokenize': False, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(WorkerDict pid=915957) kwargs: {'n': 5, 'logprobs': 0, 'max_tokens': 1024, 'detokenize': False, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(WorkerDict pid=915953) kwargs: {'n': 5, 'logprobs': 0, 'max_tokens': 1024, 'detokenize': False, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(TaskRunner pid=915150) Using LocalLogger is deprecated. The constructor API will change 
(WorkerDict pid=915761) kwargs: {'n': 5, 'logprobs': 0, 'max_tokens': 1024, 'detokenize': False, 'temperature': 1.0, 'top_k': -1, 'top_p': 1, 'ignore_eos': False}
(WorkerDict pid=915761) After building vllm rollout, memory allocated (GB): 17.29606533050537, memory reserved (GB): 24.5703125
(WorkerDict pid=915761) After building sharding manager, memory allocated (GB): 17.29606533050537, memory reserved (GB): 24.5703125
(TaskRunner pid=915150) Checkpoint tracker file does not exist: %s /home/dense/tobhaab/vlm/checkpoints/TinyZero/gsm8k_qwen2.5-7B-Instruct/latest_checkpointed_iteration.txt
(TaskRunner pid=915150) Training from scratch
(TaskRunner pid=915150) test_gen_batch meta info: {'eos_token_id': 151645, 'pad_token_id': 151643, 'recompute_log_prob': False, 'do_sample': False, 'validate': True}
(TaskRunner pid=915150) validation generation end
(TaskRunner pid=915150) [prompt] system
(TaskRunner pid=915150) You are Qwen, created by Alibaba Cloud. You are a helpful assistant.
(TaskRunner pid=915150) user
(TaskRunner pid=915150) Janet’s ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells the remainder at the farmers' market daily for $2 per fresh duck egg. How much in dollars does she make every day at the farmers' market? Let's think step by step and output the final answer after "####".
(TaskRunner pid=915150) assistant
(TaskRunner pid=915150) 
(TaskRunner pid=915150) [response] Let's break down the problem step by step:
(TaskRunner pid=915150) 
(TaskRunner pid=915150) 1. **Calculate the total number of eggs laid by Janet's ducks per day:**
(TaskRunner pid=915150)    - Janet's ducks lay 16 eggs per day.
(TaskRunner pid=915150) 
(TaskRunner pid=915150) 2. **Determine the number of eggs Janet uses for her own consumption:**
(TaskRunner pid=915150)    - Janet eats 3 eggs for breakfast every morning.
(TaskRunner pid=915150)    - She also uses 4 eggs to bake muffins for her friends.
(TaskRunner pid=915150)    - Therefore, the total number of eggs she uses is \(3 + 4 = 7\) eggs per day.
(TaskRunner pid=915150) 
(TaskRunner pid=915150) 3. **Calculate the number of eggs left to sell at the farmers' market:**
(TaskRunner pid=915150)    - The number of eggs left after Janet uses some for her own consumption is \(16 - 7 = 9\) eggs per day.
(TaskRunner pid=915150) 
Training Progress:   0%|          | 0/302 [00:00<?, ?it/s]
(TaskRunner pid=915150) 4. **Calculate the revenue from selling the remaining eggs:**
(TaskRunner pid=915150)    - Janet sells the remaining 9 eggs at the farmers' market for $2 per egg.
(TaskRunner pid=915150)    - Therefore, the revenue from selling the eggs is \(9 \times 2 = 18\) dollars per day.
(TaskRunner pid=915150) 
(TaskRunner pid=915150) #### 18
(TaskRunner pid=915150) [ground_truth] 18
(TaskRunner pid=915150) [score] 1.0
(TaskRunner pid=915150) ("Initial validation metrics: {'val/test_score/openai/gsm8k': "
(TaskRunner pid=915150)  '0.7892342683851402}')
(TaskRunner pid=915150) step:0 - val/test_score/openai/gsm8k:0.789
Error executing job with overrides: ['algorithm.adv_estimator=grpo', 'data.train_files=./data/gsm8k/train.parquet', 'data.val_files=./data/gsm8k/test.parquet', 'data.train_batch_size=128', 'data.val_batch_size=640', 'data.max_prompt_length=256', 'data.max_response_length=1024', 'actor_rollout_ref.model.path=./Qwen2.5-7B-Instruct', 'actor_rollout_ref.actor.optim.lr=1e-6', 'actor_rollout_ref.model.use_remove_padding=True', 'actor_rollout_ref.actor.ppo_mini_batch_size=64', 'actor_rollout_ref.actor.ppo_micro_batch_size=8', 'actor_rollout_ref.actor.use_kl_loss=True', 'actor_rollout_ref.actor.kl_loss_coef=0.001', 'actor_rollout_ref.actor.kl_loss_type=low_var_kl', 'actor_rollout_ref.actor.entropy_coeff=0.001', 'actor_rollout_ref.model.enable_gradient_checkpointing=True', 'actor_rollout_ref.actor.fsdp_config.param_offload=False', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=False', 'actor_rollout_ref.rollout.log_prob_micro_batch_size=8', 'actor_rollout_ref.rollout.tensor_model_parallel_size=2', 'actor_rollout_ref.rollout.name=vllm', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.4', 'actor_rollout_ref.rollout.n=5', 'actor_rollout_ref.rollout.temperature=1.0', 'actor_rollout_ref.ref.log_prob_micro_batch_size=2', 'actor_rollout_ref.ref.fsdp_config.param_offload=False', 'algorithm.kl_ctrl.kl_coef=0.001', 'trainer.critic_warmup=0', 'trainer.logger=[console]', 'trainer.default_hdfs_dir=null', 'trainer.n_gpus_per_node=8', 'trainer.nnodes=1', 'trainer.save_freq=500', 'trainer.test_freq=10', 'trainer.project_name=TinyZero', 'trainer.experiment_name=gsm8k_qwen2.5-7B-Instruct', 'trainer.total_training_steps=302', 'trainer.total_epochs=1']
Traceback (most recent call last):
  [...]
  File "/home/vlm/verl/verl/single_controller/ray/base.py", line 42, in func
    output = ray.get(output)
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
Memory on the node (IP: 53.62.148.59, ID: 3bf23f9d060d90ab1340d1259107b84e7e4a6756fdec22feaea08180) where the task (actor ID: bf8ab2d79cc7ba1c7598e41801000000, name=qr0YmkWorkerDict_0:3:WorkerDict.__init__, pid=915955, memory used=59.64GB) was running was 487.43GB / 503.71GB (0.967681), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: e6efae4192130f1b73683e956209b784d63e9f07c4f55eb75d38d9a7) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 53.62.148.59`. To see the logs of the worker, use `ray logs worker-e6efae4192130f1b73683e956209b784d63e9f07c4f55eb75d38d9a7*out -ip 53.62.148.59. Top 10 memory users:
PID     MEM(GB) COMMAND
915958  60.87   ray::WorkerDict.ref_compute_ref_log_prob
915957  60.47   ray::WorkerDict.ref_compute_ref_log_prob
915761  59.88   ray::WorkerDict.ref_compute_ref_log_prob
915955  59.64   ray::WorkerDict.ref_compute_ref_log_prob
915959  58.64   ray::WorkerDict.ref_compute_ref_log_prob
915954  58.27   ray::WorkerDict.ref_compute_ref_log_prob
915956  56.85   ray::WorkerDict.ref_compute_ref_log_prob
915953  55.48   ray::WorkerDict.ref_compute_ref_log_prob
907382  0.55    /home/miniconda3/envs/verl/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server --log_...
907312  0.35    python3 -m verl.trainer.main_ppo algorithm.adv_estimator=grpo data.train_files=./data/gsm8k/train.pa...
Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. Set max_restarts and max_task_retries to enable retry when the task crashes due to OOM. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.

**Comment by Harper-Hua** [comment]
I ran into some similar issues- when initializing the first training step it stalls with no error message and GPU utilization dropped to zero, while CPU RAM is skyrocketing. I tried to commit out #export VLLM_ATTENTION_BACKEND=XFORMERS and it worked! also this issue might be helpful to you too: #429

**Comment by tobiashaab** [comment]
Hey @Harper-Hua, thanks for the help!

I tried commenting out `export VLLM_ATTENTION_BACKEND=XFORMERS` like you mentioned, but I’m still hitting the OOM error. I also gave the fixes in #429 a shot, but had no luck!

**Comment by tobiashaab** [comment]
I am encountering two seperate warnings - that _probably_ have nothing to do with the OOM issue but it's probably best to share them anway.

- The first warning was a float warning which was fixed using the commands suggested in #1503 
- The second warning was a warning indicating that the model wasn't initialized on the GPU. I have opened a second issue for this warning since I couldn't find an existing fix (see #2263)

**Comment by YiboXue** [comment]
Have you fixed this？I met the same problem

**Comment by tobiashaab** [comment]
> Have you fixed this？I met the same problem

Hi @YiboXue,
unfortunately not, as I didn't have the time to do any more troubleshooting. Let me know if you find a solution!

**Comment by nopride03** [comment]
I solved the problem by setting trainer.val_before_train=False. You can have a try

**Comment by tobiashaab** [comment]
Thank you, @nopride03! 

I'm currently no longer working with verl which is why I'll be closing this ticket!

**Comment by woshitff** [comment]
> I solved the problem by setting trainer.val_before_train=False. You can have a try

what's the verl or vllm version? I tried this but it didn't work. My vllm vesion is 0.8.3

**Comment by woshitff** [comment]
I encountered a CPU out-of-memory issue as the training steps progressed at around 20 steps. This has delayed my training. Do you have any other training frameworks to recommend?

**Comment by tobiashaab** [comment]
Apologies for the late reply, @woshitff.

Unfortunately, I can’t name another training framework, as the ones I used encountered similar issues. I suspect that the root cause is likely related to one of the underlying libraries being used.
