### ISSUE TITLE
SGLang rollout error while running multi-turn RL [CUDA error: an illegal memory access was encountered]

### ISSUE THREAD

**Issue by macheng6** [verl-project/verl#2965]
I encountered an error while running multi-turn RL experiments on 1-node-8GPUs A100 GRPO training setup, after running   five steps normally.

## env
sglang:  0.4.6.post5
verl: 0.4.1.dev
flash-attn:  2.7.0.post2

## error
`(WorkerDict pid=135490) [2025-08-07 17:56:58 TP1] TpModelWorkerClient hit an exception: Traceback (most recent call last):
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 118, in forward_thread_func
(WorkerDict pid=135490)     self.forward_thread_func_()
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(WorkerDict pid=135490)     return func(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 151, in forward_thread_func_
(WorkerDict pid=135490)     self.worker.forward_batch_generation(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 202, in forward_batch_generation
(WorkerDict pid=135490)     logits_output, can_run_cuda_graph = self.model_runner.forward(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 1172, in forward
(WorkerDict pid=135490)     output = self._forward_raw(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 1201, in _forward_raw
(WorkerDict pid=135490)     ret = self.forward_extend(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 1140, in forward_extend
(WorkerDict pid=135490)     return self.model.forward(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(WorkerDict pid=135490)     return func(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 417, in forward
(WorkerDict pid=135490)     hidden_states = self.model(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
(WorkerDict pid=135490)     return self._call_impl(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
(WorkerDict pid=135490)     return forward_call(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 315, in forward
(WorkerDict pid=135490)     hidden_states, residual = layer(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
(WorkerDict pid=135490)     return self._call_impl(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
(WorkerDict pid=135490)     return forward_call(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 230, in forward
(WorkerDict pid=135490)     hidden_states = self.self_attn(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
(WorkerDict pid=135490)     return self._call_impl(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
(WorkerDict pid=135490)     return forward_call(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 176, in forward
(WorkerDict pid=135490)     attn_output = self.attn(q, k, v, forward_batch)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
(WorkerDict pid=135490)     return self._call_impl(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
(WorkerDict pid=135490)     return forward_call(*args, **kwargs)
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/layers/radix_attention.py", line 101, in forward
(WorkerDict pid=135490)     return forward_batch.attn_backend.forward(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/layers/attention/base_attn_backend.py", line 79, in forward
(WorkerDict pid=135490)     return self.forward_extend(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/layers/attention/flashattention_backend.py", line 639, in forward_extend
(WorkerDict pid=135490)     forward_batch.token_to_kv_pool.set_kv_buffer(
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/mem_cache/memory_pool.py", line 412, in set_kv_buffer
(WorkerDict pid=135490)     self.v_buffer[layer_id - self.start_layer][loc] = cache_v
(WorkerDict pid=135490) RuntimeError: CUDA error: an illegal memory access was encountered
(WorkerDict pid=135490) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(WorkerDict pid=135490) 
(WorkerDict pid=135490) 
(WorkerDict pid=135490) Fatal Python error: Aborted
(WorkerDict pid=135490) 
(WorkerDict pid=135490) Thread 0x00007f7fc57db640 (most recent call first):
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 324 in wait
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 607 in wait
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/tqdm/_monitor.py", line 60 in run
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 973 in _bootstrap
(WorkerDict pid=135490) 
(WorkerDict pid=135490) Thread 0x00007f8025112640 (most recent call first):
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1829 in watchdog_thread
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 953 in run
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 973 in _bootstrap
(WorkerDict pid=135490) 
(WorkerDict pid=135490) Current thread 0x00007f80908e0640 (most recent call first):
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 122 in forward_thread_func
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 953 in run
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/threading.py", line 973 in _bootstrap
(WorkerDict pid=135490) 
(WorkerDict pid=135490) Thread 0x00007f828aaeb740 (most recent call first):
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch_memory_saver/__init__.py", line 35 in pause
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/torch_memory_saver_adapter.py", line 63 in pause
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 2056 in release_memory_occupation
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/utils.py", line 471 in __call__
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 889 in process_input_requests
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 662 in event_loop_overlap
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116 in decorate_context
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 2311 in run_scheduler_process
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108 in run
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314 in _bootstrap
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/multiprocessing/spawn.py", line 129 in _main
(WorkerDict pid=135490)   File "/opt/conda/lib/python3.10/multiprocessing/spawn.py", line 116 in spawn_main
(WorkerDict pid=135490)   File "<string>", line 1 in <module>
(WorkerDict pid=135490) 
(WorkerDict pid=135490) Extension modules: msgpack._cmsgpack, google.protobuf.pyext._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, _brotli, zstandard.backend_c, uvloop.loop, ray._raylet, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, multidict._multidict, yarl._quoting_c, propcache._helpers_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, frozenlist._frozenlist, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, zmq.backend.cython._zmq, markupsafe._speedups, PIL._imaging, PIL._imagingft, av._core, av.logging, av.bytesource, av.buffer, av.audio.format, av.error, av.dictionary, av.container.pyio, av.utils, av.option, av.descriptor, av.format, av.stream, av.container.streams, av.sidedata.motionvectors, av.sidedata.sidedata, av.opaque, av.packet, av.container.input, av.container.output, av.container.core, av.codec.context, av.video.format, av.video.reformatter, av.plane, av.video.plane, av.video.frame, av.video.stream, av.codec.hwaccel, av.codec.codec, av.frame, av.audio.layout, av.audio.plane, av.audio.frame, av.audio.stream, av.filter.pad, av.filter.link, av.filter.context, av.filter.graph, av.filter.filter, av.filter.loudnorm, av.audio.resampler, av.audio.codeccontext, av.audio.fifo, av.bitstream, av.video.codeccontext, _cffi_backend, sklearn.__check_build._check_build, cython.cimports.libc.math, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.interpolate._fitpack, scipy.interpolate._dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.special.cython_special, scipy.stats._stats, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy._lib._uarray._uarray, scipy.stats._ansari_swilk_statistics, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.stats._unuran.unuran_wrapper, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.hashing, pyarrow.lib, pandas._libs.tslib, pandas._libs.ops, pyarrow._compute, pandas._libs.arrays, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, sklearn.utils._isfinite, sklearn.utils.sparsefuncs_fast, sklearn.utils.murmurhash, sklearn.utils._openmp_helpers, sklearn.metrics.cluster._expected_mutual_info_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.preprocessing._target_encoder_fast, sklearn.metrics._dist_metrics, sklearn.metrics._pairwise_distances_reduction._datasets_pair, sklearn.utils._cython_blas, sklearn.metrics._pairwise_distances_reduction._base, sklearn.metrics._pairwise_distances_reduction._middle_term_computer, sklearn.utils._heap, sklearn.utils._sorting, sklearn.metrics._pairwise_distances_reduction._argkmin, sklearn.metrics._pairwise_distances_reduction._argkmin_classmode, sklearn.utils._vector_sentinel, sklearn.metrics._pairwise_distances_reduction._radius_neighbors, sklearn.metrics._pairwise_distances_reduction._radius_neighbors_classmode, sklearn.metrics._pairwise_fast, sentencepiece._sentencepiece, ujson, msgspec._core, cuda.bindings._lib.utils, cuda.bindings._bindings.cydriver, cuda.bindings.cydriver, cuda.bindings.driver, cuda.bindings._bindings.cynvrtc, cuda.bindings.cynvrtc, cuda.bindings.nvrtc, Cython.Utils, Cython.Plex.Actions, Cython.Plex.Transitions, Cython.Plex.Machines, Cython.Plex.DFA, Cython.Plex.Scanners, Cython.Compiler.Scanning, Cython.StringIOTree, Cython.Compiler.Code, regex._regex, cuda_utils, __triton_launcher (total: 264)
(WorkerDict pid=135490) [2025-08-07 17:56:58] Received sigquit from a child process. It usually means the child failed.
(TaskRunner pid=125858) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::WorkerDict.actor_rollout_generate_sequences() (pid=135491, ip=33.145.122.250, actor_id=f8bf66349cb36de9ce7d421101000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0x7fc7d644c9d0>)
(TaskRunner pid=125858)   File "/insdata/ckpt/trl/code/agent_rl/verl/verl/single_controller/ray/base.py", line 705, in func
(TaskRunner pid=125858)     return getattr(self.worker_dict[key], name)(*args, **kwargs)
(TaskRunner pid=125858)   File "/insdata/ckpt/trl/code/agent_rl/verl/verl/single_controller/base/decorator.py", line 514, in inner
(TaskRunner pid=125858)   File "/insdata/ckpt/trl/code/agent_rl/verl/verl/workers/fsdp_workers.py", line 741, in generate_sequences
(TaskRunner pid=125858)     output = self.rollout.generate_sequences(prompts=prompts)
(TaskRunner pid=125858)   File "/insdata/ckpt/trl/code/agent_rl/verl/verl/utils/profiler/performance.py", line 89, in f
(TaskRunner pid=125858)     return self.log(decorated_function, *args, **kwargs)
(TaskRunner pid=125858)   File "/insdata/ckpt/trl/code/agent_rl/verl/verl/utils/profiler/performance.py", line 102, in log
(TaskRunner pid=125858)     output = func(*args, **kwargs)
(TaskRunner pid=125858)   File "/insdata/ckpt/trl/code/agent_rl/verl/verl/workers/rollout/sglang_rollout/sglang_rollout.py", line 576, in generate_sequences
(TaskRunner pid=125858)     return self._req_level_generate_sequences(prompts, **kwargs)
(TaskRunner pid=125858)   File "/insdata/ckpt/trl/code/agent_rl/verl/verl/utils/profiler/performance.py", line 89, in f
(TaskRunner pid=125858)     return self.log(decorated_function, *args, **kwargs)
(TaskRunner pid=125858)   File "/insdata/ckpt/trl/code/agent_rl/verl/verl/utils/profiler/performance.py", line 102, in log
(TaskRunner pid=125858)     output = func(*args, **kwargs)
(TaskRunner pid=125858)   File "/insdata/ckpt/trl/code/agent_rl/verl/verl/workers/rollout/sglang_rollout/sglang_rollout.py", line 1101, in _req_level_generate_sequences
(TaskRunner pid=125858)     dist.barrier()
(TaskRunner pid=125858)   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
(TaskRunner pid=125858)   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4556, in barrier
(TaskRunner pid=125858)     work.wait()
(TaskRunner pid=125858) RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [33.145.122.250]:41164
Training Progress:   1%|          | 1/100 [05:03<8:20:58, 303.63s/it]
Error executing job with overrides: ['algorithm.adv_estimator=grpo', 'data.train_batch_size=128', 'data.val_batch_size=4', 'data.max_prompt_length=8096', 'data.max_response_length=3000', 'data.filter_overlong_prompts=True', 'data.truncation=error', 'data.return_raw_chat=True', 'actor_rollout_ref.model.path=/mnt4/data/open_source/Qwen2.5-7B-Instruct', 'actor_rollout_ref.actor.optim.lr=1e-6', 'actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.285', 'actor_rollout_ref.model.use_remove_padding=True', 'actor_rollout_ref.actor.ppo_mini_batch_size=16', 'actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2', 'actor_rollout_ref.actor.use_kl_loss=False', 'actor_rollout_ref.actor.entropy_coeff=0', 'actor_rollout_ref.model.enable_gradient_checkpointing=True', 'actor_rollout_ref.actor.fsdp_config.param_offload=False', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=False', 'actor_rollout_ref.rollout.max_model_len=15000', 'actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4', 'actor_rollout_ref.rollout.tensor_model_parallel_size=2', 'actor_rollout_ref.rollout.name=sglang', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.7', 'actor_rollout_ref.rollout.n=2', 'actor_rollout_ref.rollout.multi_turn.max_assistant_turns=5', 'actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=2', 'actor_rollout_ref.ref.fsdp_config.param_offload=True', 'algorithm.use_kl_in_reward=False', 'trainer.critic_warmup=0', 'trainer.val_before_train=False', 'trainer.logger=["console","tensorboard"]', 'trainer.project_name=search_r1_like_async_rl', 'trainer.experiment_name=qwen2.5-3b-instruct_function_rm-hebao-async-sgl-multi-w-recalltool-verify-n16', 'trainer.n_gpus_per_node=8', 'trainer.nnodes=1', 'trainer.save_freq=100', 'trainer.test_freq=50', 'data.train_files=/insdata/ckpt/trl/code/agent_rl/data/hebao/disease_confirm_parquet/train.parquet', 'data.val_files=/insdata/ckpt/trl/code/agent_rl/data/hebao/disease_confirm_parquet/test.parquet', 'actor_rollout_ref.rollout.multi_turn.tool_config_path=/insdata/ckpt/trl/code/agent_rl/verl/examples/mc/hebao/config/tool/hebao_disease_tool_config.yaml', 'actor_rollout_ref.rollout.multi_turn.interaction_config_path=/insdata/ckpt/trl/code/agent_rl/verl/examples/mc/hebao/config/interaction/hebao_user_interaction_config.yaml', 'trainer.total_epochs=20', 'custom_reward_function.path=/insdata/ckpt/trl/code/agent_rl/verl/examples/mc/hebao/solutions/reward_fn.py']
Traceback (most recent call last):
  File "/insdata/ckpt/trl/code/agent_rl/verl/examples/mc/hebao/main_hebao.py", line 47, in main
    run_ppo(config)
  File "/insdata/ckpt/trl/code/agent_rl/verl/examples/mc/hebao/main_hebao.py", line 81, in run_ppo
    ray.get(runner.run.remote(config))
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/worker.py", line 2822, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/worker.py", line 930, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::TaskRunner.run() (pid=125858, ip=33.145.122.250, actor_id=ca0e76eda95df6a94e06c8de01000000, repr=<main_hebao.TaskRunner object at 0x7fc0c344e1a0>)
  File "/insdata/ckpt/trl/code/agent_rl/verl/examples/mc/hebao/main_hebao.py", line 257, in run
    trainer.fit()
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/trainer/ppo/ray_trainer.py", line 1170, in fit
    gen_batch_output = self.actor_rollout_wg.generate_sequences(gen_batch)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/single_controller/ray/base.py", line 50, in __call__
    output = ray.get(output)
ray.exceptions.RayTaskError(RuntimeError): ray::WorkerDict.actor_rollout_generate_sequences() (pid=135489, ip=33.145.122.250, actor_id=070882941497acf48f16e36301000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0x7ecff4318a00>)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/single_controller/ray/base.py", line 705, in func
    return getattr(self.worker_dict[key], name)(*args, **kwargs)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/single_controller/base/decorator.py", line 514, in inner
    return func(*args, **kwargs)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/workers/fsdp_workers.py", line 741, in generate_sequences
    output = self.rollout.generate_sequences(prompts=prompts)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/utils/profiler/performance.py", line 89, in f
    return self.log(decorated_function, *args, **kwargs)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/utils/profiler/performance.py", line 102, in log
    output = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/workers/rollout/sglang_rollout/sglang_rollout.py", line 576, in generate_sequences
    return self._req_level_generate_sequences(prompts, **kwargs)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/utils/profiler/performance.py", line 89, in f
    return self.log(decorated_function, *args, **kwargs)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/utils/profiler/performance.py", line 102, in log
    output = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/insdata/ckpt/trl/code/agent_rl/verl/verl/workers/rollout/sglang_rollout/sglang_rollout.py", line 1101, in _req_level_generate_sequences
    dist.barrier()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 4556, in barrier
    work.wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [33.145.122.250]:41677

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
(raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffbeab97b60ebc306ddcd1495501000000 Worker ID: ae0965d8ec4a7be8dd8ee21d876af1cdac72eeb4887c9080b9650ebf Node ID: b4ee1b9fa8de999d3fe728733bd22a1f21b69e194d9fae9cc7b5dbf0 Worker IP address: 33.145.122.250 Worker port: 45319 Worker PID: 135490 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(TaskRunner pid=125858)   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context [repeated 2x across cluster]
(TaskRunner pid=125858)     return func(*args, **kwargs) [repeated 4x across cluster]`

**Comment by Cesilina** [comment]
我这边使用sglang只开启tp的话，是能跑的，针对moe模型的话，开启ep，就会出现这个问题，也是从tp_worker_overlap_thread.py这里进入有问题的

**Comment by macheng6** [comment]
> 我这边使用sglang只开启tp的话，是能跑的，针对moe模型的话，开启ep，就会出现这个问题，也是从tp_worker_overlap_thread.py这里进入有问题的

我是qwen2.5-7b，也不是moe模型。也是tp，但是会报这个错，方便说下verl和sglang的版本吗

**Comment by Siyuexi** [comment]
Same problem. Is there any solution already?

**Comment by 2645283289** [comment]
same problem, can you share with your solution if it has been solved!

**Comment by ZenzenWang** [comment]
I'm encountering a similar issue. I'm just doing SFT on a MoE model without using sglang, but I'm hitting this problem at the start of the first epoch:
torch.AcceleratorError: CUDA error: an illegal memory access was encountered

**Comment by Kirrito-k423** [comment]
中文：感谢报告。基于目前公开信息，我不建议直接关闭这条 issue：#2965 使用的是 sglang 0.4.6.post5 / verl 0.4.1.dev，并且栈在 SGLang 的 KV cache 写入路径触发 CUDA illegal memory access；后续评论只有复现和询问，没有确认解决方案。

相关公开记录显示，这类 SGLang illegal memory access 可能和 SGLang 版本、overlap/async 路径以及显存配置有关：#1611 中有用户反馈调整 `actor_rollout_ref.rollout.gpu_memory_utilization` 可绕过某些场景（https://github.com/verl-project/verl/issues/1611#issuecomment-2933366576），但也有用户继续复现；#2365 修复了一个 SGLang async + Multi-stage Awake 的特定回归（https://github.com/verl-project/verl/pull/2365），不能直接证明本 issue 已修复；#1686 仍未合并（https://github.com/verl-project/verl/pull/1686）。verl 文档也说明 SGLang 下 `gpu_memory_utilization` 的语义不同于 vLLM，可能影响显存行为（https://github.com/verl-project/verl/blob/main/docs/perf/perf_tuning.rst）。

为了继续定位，请在最新 verl main 或最新 release + 当前推荐 SGLang 版本上确认是否仍可复现，并补充：完整可运行命令/配置、verl commit、sglang/torch/CUDA/driver 版本、GPU 型号、是否使用 multi-turn/tool use、`CUDA_LAUNCH_BLOCKING=1` 后的首个报错栈，以及调整 `gpu_memory_utilization`、`max_num_batched_tokens`、`max_num_seqs` 后是否变化。

English: Thanks for the report. Based on the current public evidence, I would not close this issue yet. #2965 was reported with sglang 0.4.6.post5 / verl 0.4.1.dev, and the stack fails inside SGLang's KV-cache write path with CUDA illegal memory access. The follow-up comments only report similar failures or ask for a solution; there is no confirmed fix in this thread.

Related public records suggest this class of SGLang illegal-memory-access failures may depend on SGLang version, overlap/async paths, and memory configuration. In #1611, one user reported that changing `actor_rollout_ref.rollout.gpu_memory_utilization` worked around their case (https://github.com/verl-project/verl/issues/1611#issuecomment-2933366576), while later reports still reproduced similar errors. #2365 fixed one specific SGLang async + Multi-stage Awake regression (https://github.com/verl-project/verl/pull/2365), but it does not directly prove this issue is fixed. #1686 is still open (https://github.com/verl-project/verl/pull/1686). The verl docs also note that `gpu_memory_utilization` has different semantics for SGLang than for vLLM and can affect memory behavior (https://github.com/verl-project/verl/blob/main/docs/perf/perf_tuning.rst).

For further triage, please verify whether this still reproduces on latest verl main or the latest release with the currently recommended SGLang version, and share: a complete runnable command/config, verl commit, sglang/torch/CUDA/driver versions, GPU type, whether multi-turn/tool use is enabled, the first stack trace with `CUDA_LAUNCH_BLOCKING=1`, and whether changing `gpu_memory_utilization`, `max_num_batched_tokens`, or `max_num_seqs` changes the failure.

This response was generated by a scheduled Codex GPT5.5 issue processing task.
