### ISSUE TITLE
[BUG] 跑多机多卡脚本时，会出现flash_attn shape mismatch或者CUDA driver error: invalid argument

### ISSUE THREAD

**Issue by PengJiazhen408** [verl-project/verl#3249]
我原来用3月份的verl，是可以跑通fsdp+vllm0.8.2的GRPO的脚本。

但安装最新的verl时，跑同样的模型和数据，会出现flash_attn shape对不上的错误：

```bash
File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/single_controller/ray/base.py", line 701, in func
    return getattr(self.worker_dict[key], name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/single_controller/base/decorator.py", line 430, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/workers/fsdp_workers.py", line 804, in compute_log_prob
    output, entropys = self.actor.compute_log_prob(data=data, calculate_entropy=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/utils/profiler/performance.py", line 105, in f
    return self.log(decorated_function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/utils/profiler/performance.py", line 118, in log
    output = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/workers/actor/dp_actor.py", line 343, in compute_log_prob
    entropy, log_probs = self._forward_micro_batch(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/workers/actor/dp_actor.py", line 177, in _forward_micro_batch
    output = self.actor_module(
             ^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 864, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 450, in forward
    outputs: BaseModelOutputWithPast = self.model(
                                       ^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 379, in forward
    hidden_states = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 864, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 231, in forward
    hidden_states, _ = self.self_attn(
                       ^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 167, in forward
    attn_output, attn_weights = attention_interface(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/transformers/integrations/flash_attention.py", line 64, in flash_attention_forward
    attn_output = _flash_attention_forward(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/models/transformers/monkey_patch.py", line 101, in _ulysses_flash_attention_forward
    attn_output = _flash_attention_forward(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/transformers/modeling_flash_attention_utils.py", line 679, in _flash_attention_forward
    out = flash_varlen_fn(
          ^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 1448, in flash_attn_varlen_func
    return FlashAttnVarlenFunc.apply(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 930, in forward
    out_padded, softmax_lse, S_dmask, rng_state = _wrapped_flash_attn_varlen_forward(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/_ops.py", line 1123, in __call__
    return self._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/_library/autograd.py", line 113, in autograd_impl
    result = forward_no_grad(*args, Metadata(keyset, keyword_only_args))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/_library/autograd.py", line 40, in forward_no_grad
    result = op.redispatch(keyset & _C._after_autograd_keyset, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/_ops.py", line 728, in redispatch
    return self._handle.redispatch_boxed(keyset, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/_library/custom_ops.py", line 305, in backend_impl
    result = self._backend_fns[device_type](*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/_compile.py", line 32, in inner
    return disable_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/_library/custom_ops.py", line 337, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 170, in _flash_attn_varlen_forward
    out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.varlen_fwd(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[1, 2, 5, 128]' is invalid for input of size 216622080

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

我将transformers的版本号从4.55降到4.49后，出现了另一个错误：

```bash
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/single_controller/ray/base.py", line 701, in func
    return getattr(self.worker_dict[key], name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/single_controller/base/decorator.py", line 430, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/workers/fsdp_workers.py", line 715, in update_actor
    metrics = self.actor.update_policy(data=data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/utils/profiler/performance.py", line 105, in f
    return self.log(decorated_function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/utils/profiler/performance.py", line 118, in log
    output = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/yongyi.hyy/verl-dapo/verl/verl/workers/actor/dp_actor.py", line 479, in update_policy
    loss.backward()
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/_tensor.py", line 626, in backward
    torch.autograd.backward(
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/autograd/graph.py", line 823, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 756, in _post_backward_hook
    _reduce_grad(state, handle)
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 838, in _reduce_grad
    padded_unsharded_grad, new_sharded_grad = _get_reduce_scatter_tensors(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/lianggui.wlg/miniforge3/envs/dapo/lib/python3.11/site-packages/torch/distributed/fsdp/_runtime_utils.py", line 891, in _get_reduce_scatter_tensors
    new_sharded_grad = torch.empty_like(chunks[0])  # padded
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA driver error: invalid argument
```

这是我的运行脚本：

```bash
set -x

# export VLLM_ATTENTION_BACKEND=XFORMERS
# export CUDA_DEVICE_MAX_CONNECTIONS=1 # For megatron communication/computation overlapping
export SWANLAB_API_KEY="sbMLhWZ5osZB7cv83Uloo"
# export CUDA_DEVICE_ORDER="PCI_BUS_ID"
#export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"
# export DISABLE_FLASH_ATTENTION=1
# export TRANSFORMERS_USE_FLASH_ATTENTION_2=0

iter=${1:-3}
exp=${2:-"sft_no_diff3"}
exp2=${3:-"grpo"}
base_model=${4:-"/mnt/model-new/xkliao/full-model-path/Qwen2.5-32B-Instruct/full-mix-traj-claude4-no-diff3"}
reward_func=${5:-"OneShotThinkReasonDetailedReward2_32b"}
next_iter=$((iter + 1))

use_kl_loss=False
kl_loss_coef=0.0

clip_ratio_low=0.4
clip_ratio_high=0.4

enable_overlong_buffer=True
overlong_buffer_len=$((1024 * 1))
overlong_penalty_factor=1.0
max_prompt_length=$((1024 * 16))
max_response_length=$((1024 * 1))

loss_agg_mode="token-mean"

loss_mode=geo_mean


# Algorithm
temperature=1.0
top_p=1.0
top_k=-1 # 0 for HF rollout, -1 for vLLM rollout
val_top_p=0.7


# Performance Related Parameter
offload=True
gen_tp=8
use_dynamic_bsz=True
actor_ppo_max_token_len=$(((max_prompt_length + max_response_length) * 2))
infer_ppo_max_token_len=$(((max_prompt_length + max_response_length) * 3))

# 读取GPU环境
MASTER_ADDR=$MASTER_ADDR
MASTER_PORT=$MASTER_PORT
GPUS_PER_NODE=$NPROC_PER_NODE
NODE_RANK=$RANK
WORLD_SIZE=2

echo $NNODES
echo $MASTER_ADDR
echo $MASTER_PORT
echo $GPUS_PER_NODE
echo $NODE_RANK
echo $WORLD_SIZE


# #model="/mnt/workspace/yongyi.hyy/ckpt/14B-1e-6-0.1-p-Qwen2.5-14B-Instruct-appworld-dpo"
# model="/mnt/model-new/xkliao/full-model-path/Qwen2.5-32B-Instruct/full-mix-claude4"
# model="/mnt/model/pengjiazhen.pjz/ckpt/14B-1e-6-0.1-p-Qwen2.5-14B-Instruct-appworld-dpo"
# model="/mnt/model/xielipeng.xlp/models/Qwen2.5-32B-Instruct"
# model="/mnt/model-new/shian.lq/iterative_rl/32B-nosft-iterative-stage2-length40000-simpo"
# base_model="/mnt/model-new/xkliao/full-model-path/Qwen2.5-32B-Instruct/full-mix-traj-claude4-no-diff3"
model_path="checkpoints/${exp}_${exp2}/iter${iter}"
if [ ! $iter -eq 0 ]; then
  step=$(< "$model_path/latest_checkpointed_iteration.txt")
  model="${model_path}/global_step_${step}/actor/huggingface"
else 
  model=$base_model
fi

if [ "$NODE_RANK" -eq 0 ]; then
  # 在容器中启动 Ray 的主节点
  ray start --head --node-ip-address=$MASTER_ADDR --port=6378 --num-gpus=$GPUS_PER_NODE
  sleep 60
  ray job submit --address="http://127.0.0.1:8265" \
    -- python3 -m verl.trainer.main_ppo --config-path=config \
        --config-name='ppo_trainer.yaml'\
        algorithm.adv_estimator=grpo \
        algorithm.kl_ctrl.kl_coef=0 \
        algorithm.use_kl_in_reward=False \
        data.train_files="logs/Qwen2.5-32B-Instruct/${exp}/${exp2}/${iter}/train.parquet" \
        data.val_files="logs/Qwen2.5-32B-Instruct/${exp}/${exp2}/${iter}/test.parquet" \
        data.train_batch_size=16 \
        data.max_prompt_length=${max_prompt_length} \
        data.max_response_length=${max_response_length} \
        data.filter_overlong_prompts=True \
        data.truncation='error' \
        actor_rollout_ref.model.path=${model} \
        actor_rollout_ref.actor.optim.lr=1e-6 \
        actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
        actor_rollout_ref.actor.optim.weight_decay=0.1 \
        actor_rollout_ref.actor.ppo_mini_batch_size=4 \
        actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
        actor_rollout_ref.actor.fsdp_config.param_offload=False \
        actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
        actor_rollout_ref.actor.ulysses_sequence_parallel_size=4 \
        actor_rollout_ref.model.use_remove_padding=True \
        +actor_rollout_ref.model.override_config.max_position_embeddings=32768 \
        actor_rollout_ref.actor.use_dynamic_bsz=${use_dynamic_bsz} \
        actor_rollout_ref.ref.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
        actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=${use_dynamic_bsz} \
        actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${actor_ppo_max_token_len} \
        actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
        actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${infer_ppo_max_token_len} \
        actor_rollout_ref.actor.use_kl_loss=${use_kl_loss} \
        actor_rollout_ref.actor.kl_loss_coef=${kl_loss_coef} \
        actor_rollout_ref.actor.policy_loss.loss_mode=${loss_mode} \
        actor_rollout_ref.actor.clip_ratio_low=${clip_ratio_low} \
        actor_rollout_ref.actor.clip_ratio_high=${clip_ratio_high} \
        actor_rollout_ref.actor.entropy_coeff=0 \
        actor_rollout_ref.actor.grad_clip=1.0 \
        actor_rollout_ref.actor.loss_agg_mode=${loss_agg_mode} \
        actor_rollout_ref.model.enable_gradient_checkpointing=True \
        actor_rollout_ref.rollout.max_num_batched_tokens=$((max_prompt_length + max_response_length)) \
        actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
        actor_rollout_ref.rollout.name=vllm \
        actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
        actor_rollout_ref.rollout.enable_chunked_prefill=False \
        actor_rollout_ref.rollout.enforce_eager=False \
        actor_rollout_ref.rollout.free_cache_engine=False \
        actor_rollout_ref.rollout.tensor_model_parallel_size=${gen_tp} \
        actor_rollout_ref.rollout.n=4 \
        actor_rollout_ref.rollout.temperature=${temperature} \
        actor_rollout_ref.rollout.top_p=${top_p} \
        actor_rollout_ref.rollout.top_k=${top_k} \
        actor_rollout_ref.rollout.val_kwargs.temperature=${temperature} \
        actor_rollout_ref.rollout.val_kwargs.top_p=${val_top_p} \
        actor_rollout_ref.rollout.val_kwargs.top_k=${top_k} \
        actor_rollout_ref.rollout.val_kwargs.do_sample=True \
        actor_rollout_ref.rollout.val_kwargs.n=1 \
        actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
        trainer.critic_warmup=0 \
        trainer.logger=['console','swanlab'] \
        trainer.project_name=${exp}_${exp2} \
        trainer.experiment_name="iter${next_iter}" \
        trainer.n_gpus_per_node=$GPUS_PER_NODE \
        trainer.nnodes=$WORLD_SIZE \
        trainer.save_freq=5 \
        trainer.test_freq=5 \
        trainer.total_epochs=1 \
        custom_reward_function.path="/mnt/workspace/pengjiazhen.pjz/code/ToolScope/Common/Reward/OneShotThinkReasonDetailedReward2_32b_markdown_gen_task.py" \
        reward_model.reward_manager=dapo \
        +reward_model.reward_kwargs.overlong_buffer_cfg.enable=${enable_overlong_buffer} \
        +reward_model.reward_kwargs.overlong_buffer_cfg.len=${overlong_buffer_len} \
        +reward_model.reward_kwargs.overlong_buffer_cfg.penalty_factor=${overlong_penalty_factor} \
        +reward_model.reward_kwargs.overlong_buffer_cfg.log=True \
        +reward_model.reward_kwargs.max_resp_len=${max_response_length}
else
  # 在更多节点上启动 Ray
  ray start --address $MASTER_ADDR:6378 --num-gpus $GPUS_PER_NODE
  python /mnt/workspace/shian.lq/RL_project/verl/scripts/null_node.py
fi
```

和我的运行环境：
```bash
Package                                  Version             Editable project location
---------------------------------------- ------------------- ----------------------------------------
absl-py                                  2.3.1
accelerate                               1.10.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.12.15
aiohttp-cors                             0.8.1
aiosignal                                1.4.0
airportsdata                             20250811
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    3.7.1
apex                                     0.1
appworld                                 0.1.3
astor                                    0.8.1
asttokens                                3.0.0
async-generator                          1.10
attrs                                    25.3.0
av                                       15.0.0
blake3                                   1.0.5
boto3                                    1.40.16
botocore                                 1.40.16
cachetools                               5.5.2
certifi                                  2025.8.3
cffi                                     1.17.1
cfgv                                     3.4.0
charset-normalizer                       3.4.3
click                                    8.2.1
cloudpickle                              3.1.1
codetiming                               1.4.0
colorful                                 0.5.7
compressed-tensors                       0.9.3
cryptography                             39.0.2
cupy-cuda12x                             13.6.0
datasets                                 4.0.0
decorator                                5.2.1
Deprecated                               1.2.18
depyf                                    0.18.0
dill                                     0.3.8
diskcache                                5.6.3
distlib                                  0.4.0
distro                                   1.9.0
dnspython                                2.7.0
einops                                   0.8.1
email_validator                          2.2.0
execnet                                  2.1.1
executing                                2.2.0
Faker                                    24.14.1
fastapi                                  0.116.1
fastapi-cli                              0.0.8
fastapi-cloud-cli                        0.1.5
fastapi-login                            1.9.3
fastrlock                                0.8.3
filelock                                 3.19.1
flash_attn                               2.7.4.post1
flashinfer-python                        0.2.4+cu124torch2.6
freezegun                                1.2.2
frozenlist                               1.7.0
fsspec                                   2025.3.0
gguf                                     0.17.1
gitdb                                    4.0.12
GitPython                                3.1.45
google-api-core                          2.25.1
google-auth                              2.40.3
googleapis-common-protos                 1.70.0
greenlet                                 3.2.4
grpcio                                   1.74.0
h11                                      0.16.0
hf_transfer                              0.1.9
hf-xet                                   1.1.8
httpcore                                 1.0.9
httptools                                0.6.4
httpx                                    0.27.2
huggingface-hub                          0.34.4
hydra-core                               1.3.2
identify                                 2.6.13
idna                                     3.10
importlib_metadata                       8.0.0
inflection                               0.5.1
iniconfig                                2.1.0
interegular                              0.3.3
ipython                                  9.4.0
ipython_pygments_lexers                  1.1.1
jedi                                     0.19.2
Jinja2                                   3.1.6
jiter                                    0.10.0
jmespath                                 1.0.1
jsonref                                  1.1.0
jsonschema                               4.25.1
jsonschema-specifications                2025.4.1
lark                                     1.2.2
libcst                                   1.8.2
liger_kernel                             0.6.2
llguidance                               0.7.30
llvmlite                                 0.44.0
lm-format-enforcer                       0.10.12
Markdown                                 3.8.2
markdown-it-py                           4.0.0
MarkupSafe                               3.0.2
mathruler                                0.1.0
matplotlib-inline                        0.1.7
mdurl                                    0.1.2
mistral_common                           1.8.4
modelscope                               1.29.0
mpmath                                   1.3.0
msgpack                                  1.1.1
msgspec                                  0.19.0
multidict                                6.6.4
multiprocess                             0.70.16
munch                                    4.0.0
nest-asyncio                             1.6.0
networkx                                 3.5
ninja                                    1.13.0
nodeenv                                  1.9.1
numba                                    0.61.2
numpy                                    1.26.4
nvidia-cublas-cu12                       12.4.5.8
nvidia-cuda-cupti-cu12                   12.4.127
nvidia-cuda-nvrtc-cu12                   12.4.127
nvidia-cuda-runtime-cu12                 12.4.127
nvidia-cudnn-cu12                        9.1.0.70
nvidia-cufft-cu12                        11.2.1.3
nvidia-curand-cu12                       10.3.5.147
nvidia-cusolver-cu12                     11.6.1.9
nvidia-cusparse-cu12                     12.3.1.170
nvidia-cusparselt-cu12                   0.6.2
nvidia-ml-py                             12.575.51
nvidia-nccl-cu12                         2.21.5
nvidia-nvjitlink-cu12                    12.4.127
nvidia-nvtx-cu12                         12.4.127
omegaconf                                2.3.0
openai                                   1.100.2
opencensus                               0.11.4
opencensus-context                       0.1.3
opencv-fixer                             0.2.5
opencv-python                            4.12.0.88
opencv-python-headless                   4.12.0.88
opentelemetry-api                        1.36.0
opentelemetry-exporter-otlp              1.26.0
opentelemetry-exporter-otlp-proto-common 1.26.0
opentelemetry-exporter-otlp-proto-grpc   1.26.0
opentelemetry-exporter-otlp-proto-http   1.26.0
opentelemetry-exporter-prometheus        0.57b0
opentelemetry-proto                      1.26.0
opentelemetry-sdk                        1.36.0
opentelemetry-semantic-conventions       0.57b0
opentelemetry-semantic-conventions-ai    0.4.12
optree                                   0.17.0
orjson                                   3.11.2
outcome                                  1.3.0.post0
outlines                                 0.1.11
outlines_core                            0.1.26
packaging                                25.0
pandas                                   2.3.2
parso                                    0.8.4
partial-json-parser                      0.2.1.1.post6
peft                                     0.17.1
pendulum                                 3.1.0
pexpect                                  4.9.0
pillow                                   11.3.0
pip                                      25.2
platformdirs                             4.3.8
pluggy                                   1.6.0
polyfactory                              2.22.2
pre_commit                               4.3.0
prettytable                              3.16.0
prometheus_client                        0.22.1
prometheus-fastapi-instrumentator        7.1.0
prompt_toolkit                           3.0.51
propcache                                0.3.2
proto-plus                               1.26.1
protobuf                                 4.25.8
psutil                                   5.9.8
ptyprocess                               0.7.0
pure_eval                                0.2.3
py-cpuinfo                               9.0.0
py-spy                                   0.4.1
pyarrow                                  21.0.0
pyasn1                                   0.6.1
pyasn1_modules                           0.4.2
pybind11                                 3.0.0
pycountry                                24.6.1
pycparser                                2.22
pydantic                                 2.11.7
pydantic_core                            2.33.2
pydantic-extra-types                     2.10.5
pyecharts                                2.0.8
Pygments                                 2.19.2
PyJWT                                    2.10.1
pylatexenc                               2.10
pynvml                                   12.0.0
pytest                                   8.4.1
pytest-xdist                             3.8.0
python-dateutil                          2.9.0.post0
python-dotenv                            1.1.1
python-json-logger                       3.3.0
python-multipart                         0.0.20
pytz                                     2025.2
pyvers                                   0.1.0
PyYAML                                   6.0.2
pyzmq                                    27.0.2
qwen-vl-utils                            0.0.11
ray                                      2.48.0
referencing                              0.36.2
regex                                    2025.7.33
registrable                              0.0.4
requests                                 2.32.5
rich                                     13.9.4
rich-toolkit                             0.15.0
rignore                                  0.6.4
rpds-py                                  0.27.0
rsa                                      4.9.1
ruff                                     0.12.10
s3transfer                               0.13.1
safetensors                              0.6.2
scipy                                    1.16.1
sentencepiece                            0.2.1
sentry-sdk                               2.35.0
setuptools                               80.9.0
shellingham                              1.5.4
simplejson                               3.20.1
six                                      1.17.0
smart_open                               7.3.0.post1
smmap                                    5.0.2
sniffio                                  1.3.1
sortedcontainers                         2.4.0
SQLAlchemy                               2.0.43
SQLAlchemy-Utils                         0.41.2
sqlalchemy2-stubs                        0.0.2a38
sqlmodel                                 0.0.24
stack-data                               0.6.3
starlette                                0.47.2
swankit                                  0.2.4
swanlab                                  0.6.8
sympy                                    1.13.1
tensorboard                              2.20.0
tensorboard-data-server                  0.7.2
tensordict                               0.9.1
tiktoken                                 0.11.0
tokenizers                               0.21.4
torch                                    2.6.0
torchaudio                               2.6.0
torchdata                                0.11.0
torchvision                              0.21.0
tqdm                                     4.67.1
traitlets                                5.14.3
transformers                             4.55.0
trio                                     0.21.0
triton                                   3.2.0
typer                                    0.16.1
typing_extensions                        4.14.1
typing-inspection                        0.4.1
tzdata                                   2025.2
urllib3                                  2.5.0
uvicorn                                  0.27.1
uvloop                                   0.19.0
verl                                     0.5.0.dev0          /mnt/workspace/yongyi.hyy/verl-dapo/verl
virtualenv                               20.34.0
vllm                                     0.8.5.post1
wandb                                    0.21.1
watchfiles                               1.1.0
wcwidth                                  0.2.13
websockets                               15.0.1
Werkzeug                                 3.1.3
wheel                                    0.45.1
wrapt                                    1.17.3
xformers                                 0.0.29.post2
xgrammar                                 0.1.18
xxhash                                   3.5.0
yarl                                     1.20.1
zipp                                     3.23.0
```

**Comment by yenanjing** [comment]
I fixed it by downgrading transformers to 4.51.1

**Comment by greenhestu** [comment]
FYI, 4.55.4 not working, 4.53.1 works

**Comment by Kirrito-k423** [comment]
English:
This issue is being closed under the scheduled stale-issue cleanup rule.

Evidence checked:
- Issue: https://github.com/verl-project/verl/issues/3249
- Comments API: https://api.github.com/repos/verl-project/verl/issues/3249/comments
- Timeline API: https://api.github.com/repos/verl-project/verl/issues/3249/timeline
- Latest public reply or public reference from an account other than the current scheduled task account (`Kirrito-k423`): 2025-09-16T00:59:17Z
- Current run date: 2026-07-18; that latest non-self public activity is more than 6 months old.

Because the most recent non-self public reply/reference is older than 6 months, this issue meets the scheduled cleanup standard and is being closed. If the author or community can still provide a current reproduction, new evidence, or additional requirement context, please comment with those details and ask maintainers to reopen, or open a new issue with updated information.

中文：
本 issue 按定时清理规则关闭。

已检查的证据：
- Issue 页面：https://github.com/verl-project/verl/issues/3249
- Comments API：https://api.github.com/repos/verl-project/verl/issues/3249/comments
- Timeline API：https://api.github.com/repos/verl-project/verl/issues/3249/timeline
- 最近一次由当前定时任务账号（`Kirrito-k423`）之外账号产生的公开回复或公开引用时间：2025-09-16T00:59:17Z
- 本轮运行日期：2026-07-18；该最近非本人公开互动已经超过 6 个月。

由于最近一次非本人公开回复/引用已经超过 6 个月，本 issue 命中定时清理标准，因此关闭。如果作者或社区成员仍能提供当前版本的复现、新证据或更完整的需求背景，请继续评论并请求维护者重开，或用更新后的信息创建新 issue。

This response was generated by a scheduled Codex GPT5.5 issue processing task.
