### ISSUE TITLE
[NPU] Ulysses Sequence Parallelism 导致 logits_rmpad 与 temperature_rmpad 维度不匹配 (Ascend NPU)

### ISSUE THREAD

**Issue by singing4you** [verl-project/verl#5957]
### System Info

----------Python Info----------
Version      : 3.10.18
Compiler     : GCC 11.2.0
Build        : ('main', 'Jun  5 2025 13:08:10')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 25.1
Directory    : /home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/pip
vllm         : 0.18.0
sglang       : not found.
ray          : 2.50.0
torch        : 2.9.0
----------verl Info-----------
Version      : 0.8.0.dev
Directory    : /home/ma-user/work/verl/verl
Commit Hash  : 866a1eaa55e3f33045ea1ca93fb24c2ee02e38f3
----------Platform Info----------
Platform     : Linux-4.19.90-vhulk2211.3.0.h1543.eulerosv2r10.aarch64-aarch64-with-glibc2.34
system       : Linux
node         : notebook-debccef5-b909-46cd-9aae-a8e5f39ecef8
release      : 4.19.90-vhulk2211.3.0.h1543.eulerosv2r10.aarch64
version      : #1 SMP Tue Jun 6 07:58:07 UTC 2023
----------Environment----------
CUDA is not available.
----------System Info----------
Failed to execute nvidia-smi command.
CPU Memory      : 1511.10 GB
GPU Count       : 0

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
在8卡NPU上训练Qwen3.5-0.8B ，sp=1的时候正常跑SFT，sp>1就报这种错误了

启动脚本如下：
```
set -x

nproc_per_node=8
save_path=/data/lab/results/test/verl
model_path=/data/lab/models/Qwen3.5-0.8B

torchrun --standalone --nnodes=1 --nproc_per_node=$nproc_per_node \
     -m verl.trainer.sft_trainer \
    data.train_files=$HOME/data/gsm8k/train.parquet \
    data.val_files=$HOME/data/gsm8k/test.parquet \
    data.micro_batch_size_per_gpu=1 \
    data.messages_key=prompt \
    optim.lr=1e-4 \
    engine=fsdp \
    engine.ulysses_sequence_parallel_size=8 \
    model.path=$model_path \
    model.use_remove_padding=true \
    trainer.default_local_dir=$save_path \
    trainer.project_name=gsm8k-sft \
    trainer.experiment_name=gsm8k-sft-qwen3.5-27b-instruct \
    trainer.logger=console \
    trainer.total_epochs=2
```

报错信息：
```
Error executing job with overrides: ['data.train_files=/home/ma-user/data/gsm8k/train.parquet', 'data.val_files=/home/ma-user/data/gsm8k/test.parquet', 'data.micro_batch_size_per_gpu=8', 'data.messages_key=prompt', 'optim.lr=1e-4', 'engine=fsdp', 'engine.ulysses_sequence_parallel_size=8', 'model.path=/data/lab/models/Qwen3.5-0.8B', 'model.use_remove_padding=true', 'trainer.default_local_dir=/data/lab/results/test/verl', 'trainer.project_name=gsm8k-sft', 'trainer.experiment_name=gsm8k-sft-qwen3.5-27b-instruct', 'trainer.logger=console', 'trainer.total_epochs=2']
Error executing job with overrides: ['data.train_files=/home/ma-user/data/gsm8k/train.parquet', 'data.val_files=/home/ma-user/data/gsm8k/test.parquet', 'data.micro_batch_size_per_gpu=8', 'data.messages_key=prompt', 'optim.lr=1e-4', 'engine=fsdp', 'engine.ulysses_sequence_parallel_size=8', 'model.path=/data/lab/models/Qwen3.5-0.8B', 'model.use_remove_padding=true', 'trainer.default_local_dir=/data/lab/results/test/verl', 'trainer.project_name=gsm8k-sft', 'trainer.experiment_name=gsm8k-sft-qwen3.5-27b-instruct', 'trainer.logger=console', 'trainer.total_epochs=2']
Traceback (most recent call last):
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 461, in main
    run_sft(config)
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 453, in run_sft
    trainer.fit()
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 385, in fit
    output = self.training_client.train_batch(data=data)
  File "/home/ma-user/work/verl/verl/single_controller/base/decorator.py", line 431, in inner
    return func(*args, **kwargs)
  File "/home/ma-user/work/verl/verl/utils/transferqueue_utils.py", line 326, in inner
    return func(*args, **kwargs)
  File "/home/ma-user/work/verl/verl/utils/profiler/profile.py", line 178, in wrapper
    return func(self_instance, *args, **kwargs_inner)
  File "/home/ma-user/work/verl/verl/workers/engine_workers.py", line 352, in train_batch
    output = self.engine.train_batch(data, loss_function=self.loss_fn)
  File "/home/ma-user/work/verl/verl/workers/engine/base.py", line 126, in train_batch
    outputs = self.forward_backward_batch(data, loss_function, forward_only=False)
  File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 613, in forward_backward_batch
    loss, meta_info = self.forward_step(micro_batch, loss_function=loss_function, forward_only=forward_only)
  File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 1148, in forward_step
    model_output = self.prepare_model_outputs(
  File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 1034, in prepare_model_outputs
    logits_rmpad.div_(temperature_rmpad.clamp(min=1e-8).unsqueeze(-1).to(logits_rmpad.dtype))
RuntimeError: inplace_div_out_npu_no_check:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:190 NPU function error: call aclnnInplaceDiv failed, error code is 161002
[ERROR] 2026-04-10-16:27:12 (PID:2446568, Device:0, RankID:0) ERR00100 PTA call acl api failed.
[PID: 2446568] 2026-04-10-16:27:12.213.351 AclNN_Parameter_Error(EZ1001): 2626 and 21008 cannot broadcast.
        TraceBack (most recent call last):
        Shape of selfRef and other can't broadcast, got [21008, 248320], [2626, 1].


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 461, in main
    run_sft(config)
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 453, in run_sft
    trainer.fit()
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 385, in fit
    output = self.training_client.train_batch(data=data)
  File "/home/ma-user/work/verl/verl/single_controller/base/decorator.py", line 431, in inner
    return func(*args, **kwargs)
  File "/home/ma-user/work/verl/verl/utils/transferqueue_utils.py", line 326, in inner
    return func(*args, **kwargs)
  File "/home/ma-user/work/verl/verl/utils/profiler/profile.py", line 178, in wrapper
    return func(self_instance, *args, **kwargs_inner)
  File "/home/ma-user/work/verl/verl/workers/engine_workers.py", line 352, in train_batch
    output = self.engine.train_batch(data, loss_function=self.loss_fn)
Traceback (most recent call last):
  File "/home/ma-user/work/verl/verl/workers/engine/base.py", line 126, in train_batch
    outputs = self.forward_backward_batch(data, loss_function, forward_only=False)
  File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 613, in forward_backward_batch
    loss, meta_info = self.forward_step(micro_batch, loss_function=loss_function, forward_only=forward_only)
  File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 1148, in forward_step
    model_output = self.prepare_model_outputs(
Traceback (most recent call last):
  File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 1034, in prepare_model_outputs
    logits_rmpad.div_(temperature_rmpad.clamp(min=1e-8).unsqueeze(-1).to(logits_rmpad.dtype))
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 461, in main
    run_sft(config)
RuntimeError: inplace_div_out_npu_no_check:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:190 NPU function error: call aclnnInplaceDiv failed, error code is 161002
[ERROR] 2026-04-10-16:27:12 (PID:2446573, Device:5, RankID:5) ERR00100 PTA call acl api failed.
[PID: 2446573] 2026-04-10-16:27:12.213.806 AclNN_Parameter_Error(EZ1001): 2626 and 21008 cannot broadcast.
        TraceBack (most recent call last):
        Shape of selfRef and other can't broadcast, got [21008, 248320], [2626, 1].

  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 453, in run_sft
    trainer.fit()
```

### Expected behavior

bug fix

**Comment by Kirrito-k423** [comment]
Thank you for the detailed bug report with reproduction steps and full error trace.

This issue with Ulysses Sequence Parallelism on Ascend NPU is related to the dimension mismatch between `logits_rmpad` and `temperature_rmpad` during the division operation.

**Root cause**: When using Ulysses SP (`engine.ulysses_sequence_parallel_size=8`), the sequence is split across multiple ranks. The `temperature_rmpad` tensor (shape [2626, 1]) is not properly distributed across SP ranks, while `logits_rmpad` (shape [21008, 248320]) reflects the distributed computation. This causes a broadcast error.

**Related PRs**:
- PR [#5963](https://github.com/verl-project/verl/pull/5963) addresses weight bucket size issues for large models
- PR [#5966](https://github.com/verl-project/verl/pull/5966) adds multiturn NPU example
- PR [#5967](https://github.com/verl-project/verl/pull/5967) adds Mindspeed patch for Ascend

**Potential fix**: The `prepare_model_outputs` function in `verl/workers/engine/fsdp/transformer_impl.py` line 1034 needs to handle the SP case properly. The `temperature_rmpad` should be replicated across SP ranks or the logits should be gathered before division.

**Workaround**:
1. Use `engine.ulysses_sequence_parallel_size=1` (no SP) as you mentioned it works
2. Or try `model.use_remove_padding=false` to disable remove padding optimization

This appears to be a known issue with NPU + Ulysses SP that needs proper handling. The VeRL team is actively working on NPU support - you may want to check the related PRs above for potential fixes.

Could you share:
- Which exact NPU model you're using (Atlas A2/A3)?
- Whether you've tried the workaround?
- If the error occurs with other models besides Qwen3.5-0.8B?

**Comment by singing4you** [comment]
> Thank you for the detailed bug report with reproduction steps and full error trace.
> 
> This issue with Ulysses Sequence Parallelism on Ascend NPU is related to the dimension mismatch between `logits_rmpad` and `temperature_rmpad` during the division operation.
> 
> **Root cause**: When using Ulysses SP (`engine.ulysses_sequence_parallel_size=8`), the sequence is split across multiple ranks. The `temperature_rmpad` tensor (shape [2626, 1]) is not properly distributed across SP ranks, while `logits_rmpad` (shape [21008, 248320]) reflects the distributed computation. This causes a broadcast error.
> 
> **Related PRs**:
> 
> * PR [#5963](https://github.com/verl-project/verl/pull/5963) addresses weight bucket size issues for large models
> * PR [#5966](https://github.com/verl-project/verl/pull/5966) adds multiturn NPU example
> * PR [#5967](https://github.com/verl-project/verl/pull/5967) adds Mindspeed patch for Ascend
> 
> **Potential fix**: The `prepare_model_outputs` function in `verl/workers/engine/fsdp/transformer_impl.py` line 1034 needs to handle the SP case properly. The `temperature_rmpad` should be replicated across SP ranks or the logits should be gathered before division.
> 
> **Workaround**:
> 
> 1. Use `engine.ulysses_sequence_parallel_size=1` (no SP) as you mentioned it works
> 2. Or try `model.use_remove_padding=false` to disable remove padding optimization
> 
> This appears to be a known issue with NPU + Ulysses SP that needs proper handling. The VeRL team is actively working on NPU support - you may want to check the related PRs above for potential fixes.
> 
> Could you share:
> 
> * Which exact NPU model you're using (Atlas A2/A3)?
> * Whether you've tried the workaround?
> * If the error occurs with other models besides Qwen3.5-0.8B?

1. 用的是昇腾910B4训练卡，应该对应的是Atlas A2
2. 使用main分支代码( commit hash `516657fa39595dd557ba34b98ae58d25d0f44e66` )，把CANN版本回退到 8.3.RC2，torch/torch_npu==2.7.1 ， torchvision==0.22.1，transformers==5.3.0 后，执行以下命令对 Qwen3.5-0.8B 进行sft
```
conda activate verl
set -x

nproc_per_node=8
save_path=/data/lab/results/test/verl
model_path=/data/lab/models/Qwen3.5-0.8B 

torchrun --standalone --nnodes=1 --nproc_per_node=$nproc_per_node \
     -m verl.trainer.sft_trainer \
    data.train_files=$HOME/data/gsm8k/train.parquet \
    data.val_files=$HOME/data/gsm8k/test.parquet \
    data.micro_batch_size_per_gpu=1 \
    data.messages_key=prompt \
    optim.lr=1e-4 \
    engine=fsdp \
    engine.ulysses_sequence_parallel_size=2 \
    model.path=$model_path \
    model.use_remove_padding=false \
    model.target_modules=all-linear \
    trainer.default_local_dir=$save_path \
    trainer.project_name=gsm8k-sft \
    trainer.experiment_name=gsm8k-sft-qwen3.5-27b-instruct \
    trainer.logger=console \
    trainer.total_epochs=2
```

sp>1的问题解决了，但会报一个张量不连续的错误：
```

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 461, in main
    run_sft(config)
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 453, in run_sft
    trainer.fit()
  File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 385, in fit
    output = self.training_client.train_batch(data=data)
  File "/home/ma-user/work/verl/verl/single_controller/base/decorator.py", line 431, in inner
    return func(*args, **kwargs)
  File "/home/ma-user/work/verl/verl/utils/transferqueue_utils.py", line 326, in inner
    return func(*args, **kwargs)
  File "/home/ma-user/work/verl/verl/utils/profiler/profile.py", line 178, in wrapper
    return func(self_instance, *args, **kwargs_inner)
  File "/home/ma-user/work/verl/verl/workers/engine_workers.py", line 352, in train_batch
    output = self.engine.train_batch(data, loss_function=self.loss_fn)
  File "/home/ma-user/work/verl/verl/workers/engine/base.py", line 126, in train_batch
    outputs = self.forward_backward_batch(data, loss_function, forward_only=False)
  File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 613, in forward_backward_batch
    loss, meta_info = self.forward_step(micro_batch, loss_function=loss_function, forward_only=forward_only)
  File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 1143, in forward_step
    raw_output = self.module(
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 856, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/peft/peft_model.py", line 1923, in forward
    return self.base_model(
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 311, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/ma-user/work/verl/verl/models/transformers/qwen3_5.py", line 188, in forward_with_normal_backend
    outputs = self.model(input_ids, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/work/verl/verl/models/transformers/qwen3_5.py", line 169, in qwen3_5_base_forward
    return self.language_model(
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/utils/generic.py", line 917, in wrapper
    output = func(self, *args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/utils/output_capturing.py", line 253, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/models/qwen3_5/modeling_qwen3_5.py", line 1372, in forward
    hidden_states = decoder_layer(
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 856, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/modeling_layers.py", line 92, in __call__
    return self._gradient_checkpointing_func(partial(super().__call__, **kwargs), *args)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/_compile.py", line 51, in inner
    return disable_fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 838, in _fn
    return fn(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 495, in checkpoint
    ret = function(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/models/qwen3_5/modeling_qwen3_5.py", line 865, in forward
    hidden_states, _ = self.self_attn(
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/models/qwen3_5/modeling_qwen3_5.py", line 774, in forward
    attn_output, attn_weights = attention_interface(
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/integrations/flash_attention.py", line 68, in flash_attention_forward
    attn_output = _flash_attention_forward(
  File "/home/ma-user/work/verl/verl/models/transformers/monkey_patch.py", line 141, in _ulysses_flash_attention_forward
    torch.distributed.all_gather(position_ids_list, position_ids, group=get_ulysses_sequence_parallel_group())
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3728, in all_gather
    work = group.allgather([tensor_list], [tensor])
RuntimeError: Tensors must be contiguous
[ERROR] 2026-04-12-16:39:00 (PID:344269, Device:7, RankID:7) ERR02002 DIST invalid type

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
对 `verl/models/transformers/monkey_patch.py` 141行代码进行修改：
`
torch.distributed.all_gather(position_ids_list, position_ids.contiguous(), group=get_ulysses_sequence_parallel_group())
`

可以跑通sft了：
```
........step:1 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:21008 - train/total_tokens(B):2.1008e-05
Epoch 1/2:   3%|███                                                                                    | 1/29 [00:50<23:47, 51.00s/it]step:2 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20605 - train/total_tokens(B):4.1613e-05
Epoch 1/2:   7%|██████                                                                                 | 2/29 [01:05<13:12, 29.36s/it]step:3 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20197 - train/total_tokens(B):6.181e-05
Epoch 1/2:  10%|█████████                                                              step:4 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19987 - train/total_tokens(B):8.1797e-05
Epoch 1/2:  14%|████████████                                                                           | 4/29 [01:24<06:44, 16.17s/it]
step:5 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20225 - train/total_tokens(B):0.000102022
Epoch 1/2:  17%|███████████████                                                                        | 5/29 [01:34<05:30, 13.77s/it]step:6 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19985 - train/total_tokens(B):0.000122007
Epoch 1/2:  21%|██████████████████                                                                     | 6/29 [01:49<05:27, 14.25s/it]step:7 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20431 - train/total_tokens(B):0.000142438
Epoch 1/2:  24%|█████████████████████                                                                  | 7/29 [01:58<04:33, 12.44s/it]step:8 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19898 - train/total_tokens(B):0.000162336
Epoch 1/2:  28%|████████████████████████                                                               | 8/29 [02:06<03:56, 11.27s/it]step:9 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20740 - train/total_tokens(B):0.000183076
Epoch 1/2:  31%|███████████████████████████                                                            | 9/29 [02:21<04:09, 12.46s/it]step:10 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20402 - train/total_tokens(B):0.000203478
Epoch 1/2:  34%|█████████████████████████████▋                                                        | 10/29 [02:31<03:41, 11.64s/it]step:11 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20548 - train/total_tokens(B):0.000224026
Epoch 1/2:  38%|████████████████████████████████▌                                                     | 11/29 [02:46<03:49, 12.73s/it]step:12 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20826 - train/total_tokens(B):0.000244852
Epoch 1/2:  41%|███████████████████████████████████▌                                                  | 12/29 [03:01<03:45, 13.26s/it]step:13 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20232 - train/total_tokens(B):0.000265084
Epoch 1/2:  45%|██████████████████████████████████████▌                                               | 13/29 [03:10<03:12, 12.03s/it]step:14 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20612 - train/total_tokens(B):0.000285696
Epoch 1/2:  48%|█████████████████████████████████████████▌                                            | 14/29 [03:22<02:59, 11.99s/it]step:15 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20497 - train/total_tokens(B):0.000306193
Epoch 1/2:  52%|████████████████████████████████████████████▍                                         | 15/29 [03:31<02:36, 11.16s/it]step:16 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19961 - train/total_tokens(B):0.000326154
Epoch 1/2:  55%|███████████████████████████████████████████████▍                                      | 16/29 [03:40<02:16, 10.51s/it]step:17 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19510 - train/total_tokens(B):0.000345664
Epoch 1/2:  59%|██████████████████████████████████████████████████▍                                   | 17/29 [03:49<02:00, 10.07s/it]step:18 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20488 - train/total_tokens(B):0.000366152
Epoch 1/2:  62%|█████████████████████████████████████████████████████▍                                | 18/29 [03:58<01:46,  9.68s/it]step:19 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19728 - train/total_tokens(B):0.00038588
Epoch 1/2:  66%|████████████████████████████████████████████████████████▎                             | 19/29 [04:07<01:35,  9.57s/it]step:20 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20049 - train/total_tokens(B):0.000405929
Epoch 1/2:  69%|███████████████████████████████████████████████████████████▎                          | 20/29 [04:16<01:24,  9.37s/it]step:21 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20983 - train/total_tokens(B):0.000426912
Epoch 1/2:  72%|██████████████████████████████████████████████████████████████▎                       | 21/29 [04:30<01:25, 10.64s/it]step:22 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19774 - train/total_tokens(B):0.000446686
Epoch 1/2:  76%|█████████████████████████████████████████████████████████████████▏                    | 22/29 [04:39<01:10, 10.06s/it]step:23 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20624 - train/total_tokens(B):0.00046731
Epoch 1/2:  79%|████████████████████████████████████████████████████████████████████▏                 | 23/29 [04:50<01:02, 10.40s/it]step:24 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20953 - train/total_tokens(B):0.000488263
Epoch 1/2:  83%|███████████████████████████████████████████████████████████████████████▏              | 24/29 [05:08<01:03, 12.67s/it]step:25 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20773 - train/total_tokens(B):0.000509036
Epoch 1/2:  86%|██████████████████████████████████████████████████████████████████████████▏           | 25/29 [05:22<00:52, 13.08s/it]step:26 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20607 - train/total_tokens(B):0.000529643
Epoch 1/2:  90%|█████████████████████████████████████████████████████████████████████████████         | 26/29 [05:33<00:37, 12.40s/it]step:27 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20203 - train/total_tokens(B):0.000549846
Epoch 1/2:  93%|████████████████████████████████████████████████████████████████████████████████      | 27/29 [05:45<00:24, 12.45s/it]step:28 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20329 - train/total_tokens(B):0.000570175
Epoch 1/2:  97%|███████████████████████████████████████████████████████████████████████████████████   | 28/29 [05:54<00:11, 11.46s/it]step:29 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20686 - train/total_tokens(B):0.000590861
Epoch 1/2: 100%|██████████████████████████████████████████████████████████████████████████████████████| 29/29 [06:03<00:00, 12.55s/it]
/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/utils/data/dataloader.py:691: UserWarning: 'pin_memory_device' is set but 'pin_memory' argument is not set, then device pinned memory won't be used.please set 'pin_memory' to true, if you need to use the device pin memory
  warnings.warn(warn_msg)
```
但是很奇怪，为什么损失是 nan? ` train/loss:nan `


3. 暂时还没有跑通过Qwen3.5其他尺寸的模型，试过在8卡910B4（32GB） 跑Qwen3.5-27B的，但是一直报oom。sp=8，gradient checkpoint开了，优化器用adam8bit 还是报oom

**Comment by mikequan0425** [comment]
It seems that you have used remove padding. The current GDN in the verl repository is the PyTorch version, which cannot support variable-length cases？

**Comment by gh-dl** [comment]
> It seems that you have used remove padding. The current GDN in the verl repository is the PyTorch version, which cannot support variable-length cases？

hit the same problem.
and setting remove padding to false in sp will raise error:

        if self.strategy in {"fsdp", "fsdp2"} and self.ulysses_sequence_parallel_size > 1:
            if model_config and not model_config.get("use_remove_padding", False):
                raise ValueError(
                    "When using sequence parallelism for actor/ref policy, you must enable `use_remove_padding`."
                )

**Comment by mikequan0425** [comment]
> 
> hit the same problem. and setting remove padding to false in sp will raise error:
> 
> ```
>     if self.strategy in {"fsdp", "fsdp2"} and self.ulysses_sequence_parallel_size > 1:
>         if model_config and not model_config.get("use_remove_padding", False):
>             raise ValueError(
>                 "When using sequence parallelism for actor/ref policy, you must enable `use_remove_padding`."
>             )
> ```

SP splits tensors along the sequence length dimension. Padding breaks even partitioning, and attention masking. Invalid padding tokens must first be removed to ensure valid SP sharding. Main branch FSDP is not support SP，you can cherrypick this pr to achieve SP: https://github.com/verl-project/verl/pull/5920.
Besides, you need to adapt the variable-length for the GDN module.

Currently, to simply get the model running, you need to disable remove padding and SP. Additionally, you can enable parameter, optimizer offload, and offload policy to reduce memory usage.

Or just use veomni as your backend，it can also work.

**Comment by lifeng7777** [comment]
> > Thank you for the detailed bug report with reproduction steps and full error trace.感谢您提供的包含重现步骤和完整错误跟踪的详细错误报告。
> > This issue with Ulysses Sequence Parallelism on Ascend NPU is related to the dimension mismatch between `logits_rmpad` and `temperature_rmpad` during the division operation.Ulysses 序列并行在 Ascend NPU 上出现的这个问题与除法运算期间 `logits_rmpad` 和 `temperature_rmpad` 之间的维度不匹配有关。
> > **Root cause**: When using Ulysses SP (`engine.ulysses_sequence_parallel_size=8`), the sequence is split across multiple ranks. The `temperature_rmpad` tensor (shape [2626, 1]) is not properly distributed across SP ranks, while `logits_rmpad` (shape [21008, 248320]) reflects the distributed computation. This causes a broadcast error.**根本原因 **：当使用 Ulysses SP（ `engine.ulysses_sequence_parallel_size=8` ）时，序列会被拆分到多个进程中。temperature_rmpad 张量（形状为 [2626, 1]）在 SP 进程间的分布不正确，而 `temperature_rmpad` 张量（形状为 [ `logits_rmpad` , 248320]）则反映了分布式计算。这会导致广播错误。
> > **Related PRs**:**相关 PR** ：
> > 
> > * PR [#5963](https://github.com/verl-project/verl/pull/5963) addresses weight bucket size issues for large modelsPR 解决了大型模型重量桶尺寸问题
> > * PR [#5966](https://github.com/verl-project/verl/pull/5966) adds multiturn NPU examplePR 添加了多回合 NPU 示例
> > * PR [#5967](https://github.com/verl-project/verl/pull/5967) adds Mindspeed patch for AscendPR 为 Ascend 添加了 Mindspeed 补丁
> > 
> > **Potential fix**: The `prepare_model_outputs` function in `verl/workers/engine/fsdp/transformer_impl.py` line 1034 needs to handle the SP case properly. The `temperature_rmpad` should be replicated across SP ranks or the logits should be gathered before division.**潜在修复方案 **： `verl/workers/engine/fsdp/transformer_impl.py` 文件第 1034 行的 `prepare_model_outputs` 函数需要正确处理 SP 情况 `temperature_rmpad` 应该在 SP 进程间复制，或者应该在除法运算之前收集 logits 值。
> > **Workaround**:**变通方法 **：
> > 
> > 1. Use `engine.ulysses_sequence_parallel_size=1` (no SP) as you mentioned it works如您所说，使用 `engine.ulysses_sequence_parallel_size=1` （不使用 SP）即可。
> > 2. Or try `model.use_remove_padding=false` to disable remove padding optimization或者尝试设置 `model.use_remove_padding=false` 来禁用移除内边距优化。
> > 
> > This appears to be a known issue with NPU + Ulysses SP that needs proper handling. The VeRL team is actively working on NPU support - you may want to check the related PRs above for potential fixes.这似乎是 NPU + Ulysses SP 的一个已知问题，需要妥善处理。VeRL 团队正在积极开发 NPU 支持——您可以查看上面相关的 PR，寻找可能的修复方案。
> > Could you share:  请问您能否分享一下：
> > 
> > * Which exact NPU model you're using (Atlas A2/A3)?您具体使用的是哪款 NPU 型号（Atlas A2/A3）？
> > * Whether you've tried the workaround?你试过这种变通方法吗？
> > * If the error occurs with other models besides Qwen3.5-0.8B?如果除了 Qwen3.5-0.8B 之外的其他型号也出现此错误？
> 
> 1. 用的是昇腾910B4训练卡，应该对应的是Atlas A2
> 2. 使用main分支代码( commit hash `516657fa39595dd557ba34b98ae58d25d0f44e66` )，把CANN版本回退到 8.3.RC2，torch/torch_npu==2.7.1 ， torchvision==0.22.1，transformers==5.3.0 后，执行以下命令对 Qwen3.5-0.8B 进行sft
> 
> ```
> conda activate verl
> set -x
> 
> nproc_per_node=8
> save_path=/data/lab/results/test/verl
> model_path=/data/lab/models/Qwen3.5-0.8B 
> 
> torchrun --standalone --nnodes=1 --nproc_per_node=$nproc_per_node \
>      -m verl.trainer.sft_trainer \
>     data.train_files=$HOME/data/gsm8k/train.parquet \
>     data.val_files=$HOME/data/gsm8k/test.parquet \
>     data.micro_batch_size_per_gpu=1 \
>     data.messages_key=prompt \
>     optim.lr=1e-4 \
>     engine=fsdp \
>     engine.ulysses_sequence_parallel_size=2 \
>     model.path=$model_path \
>     model.use_remove_padding=false \
>     model.target_modules=all-linear \
>     trainer.default_local_dir=$save_path \
>     trainer.project_name=gsm8k-sft \
>     trainer.experiment_name=gsm8k-sft-qwen3.5-27b-instruct \
>     trainer.logger=console \
>     trainer.total_epochs=2
> ```
> 
> sp>1的问题解决了，但会报一个张量不连续的错误：
> 
> ```
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> Traceback (most recent call last):
>   File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 461, in main
>     run_sft(config)
>   File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 453, in run_sft
>     trainer.fit()
>   File "/home/ma-user/work/verl/verl/trainer/sft_trainer.py", line 385, in fit
>     output = self.training_client.train_batch(data=data)
>   File "/home/ma-user/work/verl/verl/single_controller/base/decorator.py", line 431, in inner
>     return func(*args, **kwargs)
>   File "/home/ma-user/work/verl/verl/utils/transferqueue_utils.py", line 326, in inner
>     return func(*args, **kwargs)
>   File "/home/ma-user/work/verl/verl/utils/profiler/profile.py", line 178, in wrapper
>     return func(self_instance, *args, **kwargs_inner)
>   File "/home/ma-user/work/verl/verl/workers/engine_workers.py", line 352, in train_batch
>     output = self.engine.train_batch(data, loss_function=self.loss_fn)
>   File "/home/ma-user/work/verl/verl/workers/engine/base.py", line 126, in train_batch
>     outputs = self.forward_backward_batch(data, loss_function, forward_only=False)
>   File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 613, in forward_backward_batch
>     loss, meta_info = self.forward_step(micro_batch, loss_function=loss_function, forward_only=forward_only)
>   File "/home/ma-user/work/verl/verl/workers/engine/fsdp/transformer_impl.py", line 1143, in forward_step
>     raw_output = self.module(
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 856, in forward
>     output = self._fsdp_wrapped_module(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/peft/peft_model.py", line 1923, in forward
>     return self.base_model(
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 311, in forward
>     return self.model.forward(*args, **kwargs)
>   File "/home/ma-user/work/verl/verl/models/transformers/qwen3_5.py", line 188, in forward_with_normal_backend
>     outputs = self.model(input_ids, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ma-user/work/verl/verl/models/transformers/qwen3_5.py", line 169, in qwen3_5_base_forward
>     return self.language_model(
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/utils/generic.py", line 917, in wrapper
>     output = func(self, *args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/utils/output_capturing.py", line 253, in wrapper
>     outputs = func(self, *args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/models/qwen3_5/modeling_qwen3_5.py", line 1372, in forward
>     hidden_states = decoder_layer(
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 856, in forward
>     output = self._fsdp_wrapped_module(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/modeling_layers.py", line 92, in __call__
>     return self._gradient_checkpointing_func(partial(super().__call__, **kwargs), *args)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/_compile.py", line 51, in inner
>     return disable_fn(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 838, in _fn
>     return fn(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 495, in checkpoint
>     ret = function(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/models/qwen3_5/modeling_qwen3_5.py", line 865, in forward
>     hidden_states, _ = self.self_attn(
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/models/qwen3_5/modeling_qwen3_5.py", line 774, in forward
>     attn_output, attn_weights = attention_interface(
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/transformers/integrations/flash_attention.py", line 68, in flash_attention_forward
>     attn_output = _flash_attention_forward(
>   File "/home/ma-user/work/verl/verl/models/transformers/monkey_patch.py", line 141, in _ulysses_flash_attention_forward
>     torch.distributed.all_gather(position_ids_list, position_ids, group=get_ulysses_sequence_parallel_group())
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
>     return func(*args, **kwargs)
>   File "/home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3728, in all_gather
>     work = group.allgather([tensor_list], [tensor])
> RuntimeError: Tensors must be contiguous
> [ERROR] 2026-04-12-16:39:00 (PID:344269, Device:7, RankID:7) ERR02002 DIST invalid type
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> ```
> 
> 对 `verl/models/transformers/monkey_patch.py` 141行代码进行修改：对 `verl/models/transformers/monkey_patch.py`​​ 141 行代码进行修改： `torch.distributed.all_gather(position_ids_list, position_ids.contiguous(), group=get_ulysses_sequence_parallel_group())`
> 
> 可以跑通sft了：
> 
> ```
> ........step:1 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:21008 - train/total_tokens(B):2.1008e-05
> Epoch 1/2:   3%|███                                                                                    | 1/29 [00:50<23:47, 51.00s/it]step:2 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20605 - train/total_tokens(B):4.1613e-05
> Epoch 1/2:   7%|██████                                                                                 | 2/29 [01:05<13:12, 29.36s/it]step:3 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20197 - train/total_tokens(B):6.181e-05
> Epoch 1/2:  10%|█████████                                                              step:4 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19987 - train/total_tokens(B):8.1797e-05
> Epoch 1/2:  14%|████████████                                                                           | 4/29 [01:24<06:44, 16.17s/it]
> step:5 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20225 - train/total_tokens(B):0.000102022
> Epoch 1/2:  17%|███████████████                                                                        | 5/29 [01:34<05:30, 13.77s/it]step:6 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19985 - train/total_tokens(B):0.000122007
> Epoch 1/2:  21%|██████████████████                                                                     | 6/29 [01:49<05:27, 14.25s/it]step:7 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20431 - train/total_tokens(B):0.000142438
> Epoch 1/2:  24%|█████████████████████                                                                  | 7/29 [01:58<04:33, 12.44s/it]step:8 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19898 - train/total_tokens(B):0.000162336
> Epoch 1/2:  28%|████████████████████████                                                               | 8/29 [02:06<03:56, 11.27s/it]step:9 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20740 - train/total_tokens(B):0.000183076
> Epoch 1/2:  31%|███████████████████████████                                                            | 9/29 [02:21<04:09, 12.46s/it]step:10 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20402 - train/total_tokens(B):0.000203478
> Epoch 1/2:  34%|█████████████████████████████▋                                                        | 10/29 [02:31<03:41, 11.64s/it]step:11 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20548 - train/total_tokens(B):0.000224026
> Epoch 1/2:  38%|████████████████████████████████▌                                                     | 11/29 [02:46<03:49, 12.73s/it]step:12 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20826 - train/total_tokens(B):0.000244852
> Epoch 1/2:  41%|███████████████████████████████████▌                                                  | 12/29 [03:01<03:45, 13.26s/it]step:13 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20232 - train/total_tokens(B):0.000265084
> Epoch 1/2:  45%|██████████████████████████████████████▌                                               | 13/29 [03:10<03:12, 12.03s/it]step:14 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20612 - train/total_tokens(B):0.000285696
> Epoch 1/2:  48%|█████████████████████████████████████████▌                                            | 14/29 [03:22<02:59, 11.99s/it]step:15 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20497 - train/total_tokens(B):0.000306193
> Epoch 1/2:  52%|████████████████████████████████████████████▍                                         | 15/29 [03:31<02:36, 11.16s/it]step:16 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19961 - train/total_tokens(B):0.000326154
> Epoch 1/2:  55%|███████████████████████████████████████████████▍                                      | 16/29 [03:40<02:16, 10.51s/it]step:17 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19510 - train/total_tokens(B):0.000345664
> Epoch 1/2:  59%|██████████████████████████████████████████████████▍                                   | 17/29 [03:49<02:00, 10.07s/it]step:18 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20488 - train/total_tokens(B):0.000366152
> Epoch 1/2:  62%|█████████████████████████████████████████████████████▍                                | 18/29 [03:58<01:46,  9.68s/it]step:19 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19728 - train/total_tokens(B):0.00038588
> Epoch 1/2:  66%|████████████████████████████████████████████████████████▎                             | 19/29 [04:07<01:35,  9.57s/it]step:20 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20049 - train/total_tokens(B):0.000405929
> Epoch 1/2:  69%|███████████████████████████████████████████████████████████▎                          | 20/29 [04:16<01:24,  9.37s/it]step:21 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20983 - train/total_tokens(B):0.000426912
> Epoch 1/2:  72%|██████████████████████████████████████████████████████████████▎                       | 21/29 [04:30<01:25, 10.64s/it]step:22 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:19774 - train/total_tokens(B):0.000446686
> Epoch 1/2:  76%|█████████████████████████████████████████████████████████████████▏                    | 22/29 [04:39<01:10, 10.06s/it]step:23 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20624 - train/total_tokens(B):0.00046731
> Epoch 1/2:  79%|████████████████████████████████████████████████████████████████████▏                 | 23/29 [04:50<01:02, 10.40s/it]step:24 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20953 - train/total_tokens(B):0.000488263
> Epoch 1/2:  83%|███████████████████████████████████████████████████████████████████████▏              | 24/29 [05:08<01:03, 12.67s/it]step:25 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20773 - train/total_tokens(B):0.000509036
> Epoch 1/2:  86%|██████████████████████████████████████████████████████████████████████████▏           | 25/29 [05:22<00:52, 13.08s/it]step:26 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20607 - train/total_tokens(B):0.000529643
> Epoch 1/2:  90%|█████████████████████████████████████████████████████████████████████████████         | 26/29 [05:33<00:37, 12.40s/it]step:27 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20203 - train/total_tokens(B):0.000549846
> Epoch 1/2:  93%|████████████████████████████████████████████████████████████████████████████████      | 27/29 [05:45<00:24, 12.45s/it]step:28 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20329 - train/total_tokens(B):0.000570175
> Epoch 1/2:  97%|███████████████████████████████████████████████████████████████████████████████████   | 28/29 [05:54<00:11, 11.46s/it]step:29 - train/loss:nan - train/grad_norm:0.0 - train/lr:0.0001 - train/mfu:0.0 - train/global_tokens:20686 - train/total_tokens(B):0.000590861
> Epoch 1/2: 100%|██████████████████████████████████████████████████████████████████████████████████████| 29/29 [06:03<00:00, 12.55s/it]
> /home/ma-user/anaconda3/envs/verl/lib/python3.10/site-packages/torch/utils/data/dataloader.py:691: UserWarning: 'pin_memory_device' is set but 'pin_memory' argument is not set, then device pinned memory won't be used.please set 'pin_memory' to true, if you need to use the device pin memory
>   warnings.warn(warn_msg)
> ```
> 
> 但是很奇怪，为什么损失是 nan? `train/loss:nan`
> 
> 3. 暂时还没有跑通过Qwen3.5其他尺寸的模型，试过在8卡910B4（32GB） 跑Qwen3.5-27B的，但是一直报oom。sp=8，gradient checkpoint开了，优化器用adam8bit 还是报oom

您27b解决oom了么？我目前也一直oom
